### ISSUE TITLE
Alterar a licença

### ISSUE THREAD

**Issue by gab0gomes** [caecom/lib-tccs#1]
Acredito que a licença atual do repositório não faz muito sentido. Tanto por não ser um software, quanto por permitir alterações nos documentos. E além disso, permitir a venda.

**Comment by ruanmed** [comment]
Então, eu só fiquei sem ideia e aí resolvi colocar a mesma licença do template. 😅 

Qual seria a sugestão, GLPv3? Ou alguma Creative Commons? 
Talvez seja bom ver como funciona o licenciamento dos TCCs da Universidade, é vedado a utilização comercial dos resultados obtidos? Achava que tudo era permitido.

**Comment by gab0gomes** [comment]
Vale investigar. Não conheço muitas licenças.
