### ISSUE TITLE
Criar CONTRIBUTING.md

### ISSUE THREAD

**Issue by ruanmed** [caecom/lib-tccs#2]
Criar um arquivo `CONTRIBUTING.md` orientando:

* Tipos de arquivos aceitos;
* Nomeação recomendada dos arquivos; (eu comecei seguindo `{ano}-{nome-completo-minúsculo}.pdf`, seria interessante manter um padrão.)
* Como os discentes podem adicionar seus TCCs; (fazer um fork, colocar o pdf na pasta pdfs e então inserir linha no README na posição correta, colocar o link para os seus repositórios)
* Outras coisas que venham a ser necessárias.

Um modelo de CONTRIBUTING.md pode ser encontrado no [OpenSource Guide](https://github.com/github/opensource.guide/blob/master/CONTRIBUTING.md), está em inglês, mas como nosso repositório é todo em PT-BR, acredito que devemos fazer o CONTRIBUTING em PT-BR mesmo para facilitar o acesso ao público-alvo.

**Comment by japbastos** [comment]
Peguei esse como meu primeiro PR pra HacktoberPest 2020 e já estou trabalhando nele.

**Comment by gab0gomes** [comment]
resolvido no https://github.com/caecom/lib-tccs/pull/4
